name: Apply plan

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  plan:
    runs-on: ubuntu-latest
    name: Apply terraform plan
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: terraform init
        run: terraform init
      - name: terraform apply
        env:
          PASSWORD: ${{ secrets.PASSWORD }}
        run: terraform plan -var=$PASSWORD
        
      #  uses: dflook/terraform-apply@v1
      # with:
      #   path: xcp-ng
