name: Apply plan

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  plan:
    runs-on: ubuntu-latest
    name: Apply terraform plan
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: terraform init
        run: terraform init
      - name: Write var file
        env:
          PASSWORD_FILE: ./variable-values.tfvars
          PASSWORD: ${{ secrets.PASSWORD }}
        run:
          echo 'password = "${PASSWORD}"' > $PASSWORD_FILE
      - name: Terraform Apply
        run:
          terraform apply -var-file=$PASSWORD_FILE
     
        
      #  uses: dflook/terraform-apply@v1
      # with:
      #   path: xcp-ng
